### ISSUE TITLE
Minimize process spawning

### ISSUE THREAD

**Issue by gmerlino** [MDSLab/s4t-lightning-rod#19]
At the moment any plugin loaded at runtime gets spawned as an additional (child) process.

An alternative implementation seeking to reduce the load of any further Node.js process, in place of requiring+spawning code, should try to:
- use eval as a way to load code at runtime
- just drop any reference to process spawning, only spawning one to keep core LR separate for all (non-critical, e.g., user/developer-provided plugins)
  - in the end there should always be 2 processes: one for LR(+critical stuff) and one executing code off _all_ (non-critical) plugins
- don't resort to threads if not strictly needed
  - we expect Threads A Go Go and similar stuff to be optional, if no plugins are CPU-bound (thus leaving any plugin that hits I/O to trigger the next ``tick'' on the event loop, i.e., switching context to another section of the code, e.g., another plugin)

This is obviously not too robust, e.g., a bug in any of the running plugins possibly brings down/hangs all the other plugins, but it is not that critical either, given the segregation of all non-critical code in a separate process.

**Comment by flongo82** [comment]
Note that here we are talking about user-developed plugins, not plugins related to core/non-core functionalities of lightning-rod, e.g., network management (those will be implemented as lightning-rod modules and will not be spawned as different plugins).
